@startuml
participant AppController
participant CompositeQuery

AppController->CompositeQuery: getData() async request
CompositeQuery->AppController: update lexeme data event
CompositeQuery->AppController: update morphology event
CompositeQuery->AppController: update definitions event
@enduml