@startuml
skinparam packageStyle rectangle
skinparam usecase {
  ArrowColor<< browserExtension >> black
  ArrowColor<< embeddedLibrary >> blue
  ArrowColor<< readerApp >> red
  BorderColor gray

}
skinparam actor {
  BorderColor<< browserExtension >> black
  BorderColor<< embeddedLibrary >> blue
  BorderColor<< readerApp >> red

}
	
actor user1 <<browserExtension>>
rectangle userstories {
  user1 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/core-user-stories.csv core]]) <<browserExtension>>
  user1 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/auth-user-stories.csv auth]]) <<browserExtension>>
  user1 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/config-user-stories.csv config]]) <<browserExtension>>
  user1 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/browserextension-user-stories.csv browserext]]) <<browserExtension>>
  user1 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/offline-user-stories.csv offline]]) <<browserExtension>>
  
}
actor user2 <<embeddedLibrary>>
rectangle userstories {
  user2 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/core-user-stories.csv core]]) <<embeddedLibrary>>
  user2 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/auth-user-stories.csv auth]]) <<embeddedLibrary>>
  user2 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/mobile-user-stories.csv mobile]]) <<embeddedLibrary>>
  user2 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/config-user-stories.csv config]]) <<embeddedLibrary>>
  user2 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/embedlib-user-stories.csv embedlib]]) <<embeddedLibrary>>
  user2 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/offline-user-stories.csv offline]]) <<embeddedLibrary>>
  
}
actor user3 <<readerApp>>
rectangle userstories {
  user3 -up--> ([[https://github.com/alpheios-project/documentation/blob/master/design/core-user-stories.csv core]]) <<readerApp>>
  user3 -up--> ([[https://github.com/alpheios-project/documentation/blob/master/design/auth-user-stories.csv auth]]) <<readerApp>>
  user3 -up--> ([[https://github.com/alpheios-project/documentation/blob/master/design/reader-user-stories.csv reader]]) <<readerApp>>
  user3 -up--> ([[https://github.com/alpheios-project/documentation/blob/master/design/mobile-user-stories.csv mobile]]) <<readerApp>>
  user3 -up--> ([[https://github.com/alpheios-project/documentation/blob/master/design/config-user-stories.csv config]]) <<readerApp>>
  user3 --> ([[https://github.com/alpheios-project/documentation/blob/master/design/offline-user-stories.csv offline]]) <<readerApp>>
  
}
@enduml
