@startuml
title A STANDARD DEVELOPMENT WORKFLOW\n notes in green indicates when version is changed\n those commits are tagged and pushed to npm\n yellow boxes are branches
participant "master\n development" as mst
participant "feature-a\n (minor feature)" as f1
participant "feature-b\n (patch feature)" as f2
participant "feature-c\n (patch feature)" as f3
participant "qa\n" as qa
participant "qa-fixes-1.3.1\n ad-hoc qa fixes" as qafix
participant "qa-fixes-1.3.21\n ad-hoc qa fixes" as qafix2
participant "release\n" as rel
participant "production\n" as prod

note over mst #FFAAAA: v1.2.3-dev.3
mst -> f1: Start a development of feature A
note over f1 #FFAAAA: v1.2.3-dev.3
f1 -> f1: Develop a new feature
mst -> f2: Start a development of feature B
note over f2 #FFAAAA: v1.2.3-dev.3
f1 --> f1: Dev test
f2 -> f2: Develop a new feature
f1 -> f1: Fix issues
note over f1 #FFAAAA: v1.2.3-dev.3
mst -> f1: Merge upstream changes (if any)
f1 -> mst: Feature A dev is complete (minor)
note over mst #GreenYellow: v1.3.0-dev.0

f2 --> f2: Dev test
f2 -> f2: Fix issues
note over f2 #FFAAAA: v1.2.3-dev.3
mst -> f2: Merge upstream changes (if any)
f2 -> mst: Feature B dev is complete (patch)
note over mst #GreenYellow: v1.3.1-dev.0

mst -> qa: Add a set of changes to QA
note over qa #GreenYellow: v1.3.1-qa.0
qa --> qa: Testing
qa -> qafix: Bugs found
note over qafix #FFAAAA: v1.3.1-qa.0
qafix -> qafix: Bug fixing
note over qafix #FFAAAA: v1.3.1-qa.0
qafix -> qa: Bugs fixed
note over qa #GreenYellow: v1.3.1-qa.1

mst -> f3: Start a development of feature C
note over f3 #FFAAAA: v1.3.1-dev.0
f3 -> f3: Develop a new feature
f3 --> f3: Dev test
f3 -> f3: Fix issues
note over f3 #FFAAAA: v1.3.1-dev.0
mst -> f3: Merge upstream changes (if any)
note over f3 #FFAAAA: v1.3.1-dev.1
f3 -> mst: Feature C dev is complete (patch)
note over mst #GreenYellow: v1.3.2-dev.0

qa --> qa: Testing
qa -> rel: Changes approved
note over rel #GreenYellow: v1.3.1-rel.0
rel -> mst: Merge fixes back
note over mst #GreenYellow: v1.3.2-dev.1

mst -> qa: Add a new set of changes to QA
note over qa #GreenYellow: v1.3.2-qa.0
qa --> qa: Testing
qa -> qafix2: Bugs found
note over qafix2 #FFAAAA: v1.3.2-qa.0
qafix2 -> qafix2: Bug fixing
note over qafix2 #FFAAAA: v1.3.2-qa.0
qafix2 -> qa: Bugs fixed
note over qa #GreenYellow: v1.3.2-qa.1
qa --> qa: Testing
qa -> rel: Changes approved
note over rel #GreenYellow: v1.3.2-rel.0
rel -> mst: Merge fixes back

rel -> prod: Release to production
note over prod #GreenYellow: v1.3.2
@enduml
